server:
  port: 8761
spring:
  application:
    name: eureka-server
eureka:
  instance:
    hostname: 127.0.0.1
  server:
    enable-self-preservation: true
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
